// Currículo completo de Quechua - 5 meses
// Fase 1: Principiante (3 meses) | Fase 2: Intermedio (1 mes) | Fase 3: Avanzado (1 mes)
import type { Unit } from "./content";

export const CURRICULUM_DATA: Unit[] = [
  // ========== FASE 1: PRINCIPIANTE - MES 1 ==========
  {
    id: "p1u1",
    title: "Mes 1 · Semana 1",
    subtitle: "Primeros Pasos",
    color: "green",
    emoji: "🌱",
    description: "Saludos básicos y presentaciones. Tu primer contacto con el Runa Simi.",
    lessons: [
      {
        id: "p1u1l1",
        title: "Saludos Básicos",
        emoji: "👋",
        description: "Aprende a saludar en quechua",
        xpReward: 15,
        gemReward: 5,
        exercises: [
          { id: "p1u1l1e1", type: "select", prompt: "allinllachu", hint: "Saludo formal", audio: "allinllachu", choices: ["Hola / Buenos días", "Adiós", "Gracias", "Perdón"], answer: "Hola / Buenos días" },
          { id: "p1u1l1e2", type: "select", prompt: "imaynallam", hint: "Pregunta amable", audio: "imaynallam", choices: ["¿Cómo estás?", "¿Cómo te llamas?", "¿De dónde eres?", "¿Qué haces?"], answer: "¿Cómo estás?" },
          { id: "p1u1l1e3", type: "select", prompt: "allinmi", hint: "Respuesta positiva", audio: "allinmi", choices: ["Estoy bien", "Estoy triste", "Estoy cansado", "No sé"], answer: "Estoy bien" },
          { id: "p1u1l1e4", type: "reverse", prompt: "Hola", hint: "Saludo general", audio: "allinllachu", choices: ["allinllachu", "tupananchiskama", "sulpayki", "payllasunki"], answer: "allinllachu" },
          { id: "p1u1l1e5", type: "listen", prompt: "¿Qué escuchaste?", hint: "Saludo", audio: "allinllachu", choices: ["Hola / Buenos días", "Gracias", "Adiós", "Perdón"], answer: "Hola / Buenos días" },
          { id: "p1u1l1e6", type: "match", prompt: "Empareja los saludos", pairs: [
            { q: "allinllachu", a: "Hola" },
            { q: "imaynallam", a: "¿Cómo estás?" },
            { q: "allinmi", a: "Estoy bien" },
            { q: "tupananchiskama", a: "Hasta luego" },
          ]},
        ],
      },
      {
        id: "p1u1l2",
        title: "Presentación",
        emoji: "🤝",
        description: "Dime tu nombre y de dónde eres",
        xpReward: 15,
        gemReward: 5,
        exercises: [
          { id: "p1u1l2e1", type: "select", prompt: "sutiyqa", hint: "Nombre propio", audio: "sutiyqa", choices: ["Mi nombre es", "Tu nombre es", "Su nombre es", "El nombre"], answer: "Mi nombre es" },
          { id: "p1u1l2e2", type: "select", prompt: "imamanta kanki", hint: "Origen", audio: "imamanta kanki", choices: ["¿De dónde eres?", "¿Cómo te llamas?", "¿Qué haces?", "¿Cuántos años tienes?"], answer: "¿De dónde eres?" },
          { id: "p1u1l2e3", type: "reverse", prompt: "Gracias", audio: "sulpayki", choices: ["sulpayki", "payllasunki", "allinllachu", "imaynallam"], answer: "sulpayki" },
          { id: "p1u1l2e4", type: "reverse", prompt: "De nada", audio: "payllasunki", choices: ["payllasunki", "sulpayki", "allinmi", "allinllachu"], answer: "payllasunki" },
          { id: "p1u1l2e5", type: "bank", prompt: "Traduce: Mi nombre es", words: ["sutiyqa", "allinmi", "imaynallam", "sulpayki"], answer: ["sutiyqa"] },
          { id: "p1u1l2e6", type: "listen", prompt: "¿Qué escuchaste?", audio: "sulpayki", choices: ["Gracias", "De nada", "Hola", "Adiós"], answer: "Gracias" },
        ],
      },
      {
        id: "p1u1l3",
        title: "Despedidas",
        emoji: "👋",
        description: "Aprende a despedirte",
        xpReward: 15,
        gemReward: 5,
        exercises: [
          { id: "p1u1l3e1", type: "select", prompt: "tupananchiskama", hint: "Despedida", audio: "tupananchiskama", choices: ["Hasta luego", "Hola", "Gracias", "Perdón"], answer: "Hasta luego" },
          { id: "p1u1l3e2", type: "select", prompt: "allin tuta", hint: "Noche", audio: "allin tuta", choices: ["Buenas noches", "Buenos días", "Buenas tardes", "Adiós"], answer: "Buenas noches" },
          { id: "p1u1l3e3", type: "select", prompt: "allin p'unchaw", hint: "Día", audio: "allin p'unchaw", choices: ["Buen día", "Buenas noches", "Hasta luego", "Gracias"], answer: "Buen día" },
          { id: "p1u1l3e4", type: "match", prompt: "Empareja", pairs: [
            { q: "tupananchiskama", a: "Hasta luego" },
            { q: "allin tuta", a: "Buenas noches" },
            { q: "allin p'unchaw", a: "Buen día" },
            { q: "sulpayki", a: "Gracias" },
          ]},
          { id: "p1u1l3e5", type: "listen", prompt: "¿Qué escuchaste?", audio: "tupananchiskama", choices: ["Hasta luego", "Hola", "Gracias", "Buen día"], answer: "Hasta luego" },
          { id: "p1u1l3e6", type: "bank", prompt: "Traduce: Buenas noches", words: ["allin", "tuta", "p'unchaw", "allinllachu"], answer: ["allin", "tuta"] },
        ],
      },
    ],
  },
  {
    id: "p1u2",
    title: "Mes 1 · Semana 2",
    subtitle: "Números y Familia",
    color: "emerald",
    emoji: "🔢",
    description: "Aprende los números del 1 al 10 y los miembros de la familia.",
    lessons: [
      {
        id: "p1u2l1",
        title: "Números 1-5",
        emoji: "1️⃣",
        description: "Cuenta del uno al cinco",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p1u2l1e1", type: "select", prompt: "huk", audio: "huk", choices: ["Uno", "Dos", "Tres", "Cuatro"], answer: "Uno" },
          { id: "p1u2l1e2", type: "select", prompt: "iskay", audio: "iskay", choices: ["Dos", "Uno", "Cinco", "Tres"], answer: "Dos" },
          { id: "p1u2l1e3", type: "select", prompt: "kimsa", audio: "kimsa", choices: ["Tres", "Dos", "Cuatro", "Cinco"], answer: "Tres" },
          { id: "p1u2l1e4", type: "select", prompt: "tawa", audio: "tawa", choices: ["Cuatro", "Cinco", "Uno", "Tres"], answer: "Cuatro" },
          { id: "p1u2l1e5", type: "select", prompt: "pisqa", audio: "pisqa", choices: ["Cinco", "Cuatro", "Dos", "Seis"], answer: "Cinco" },
          { id: "p1u2l1e6", type: "match", prompt: "Empareja los números", pairs: [
            { q: "huk", a: "Uno" }, { q: "iskay", a: "Dos" }, { q: "kimsa", a: "Tres" }, { q: "tawa", a: "Cuatro" }, { q: "pisqa", a: "Cinco" },
          ]},
          { id: "p1u2l1e7", type: "reverse", prompt: "Tres", audio: "kimsa", choices: ["kimsa", "iskay", "tawa", "pisqa"], answer: "kimsa" },
        ],
      },
      {
        id: "p1u2l2",
        title: "Números 6-10",
        emoji: "6️⃣",
        description: "Continúa contando del seis al diez",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p1u2l2e1", type: "select", prompt: "suqta", audio: "suqta", choices: ["Seis", "Siete", "Ocho", "Cinco"], answer: "Seis" },
          { id: "p1u2l2e2", type: "select", prompt: "qanchis", audio: "qanchis", choices: ["Siete", "Seis", "Ocho", "Nueve"], answer: "Siete" },
          { id: "p1u2l2e3", type: "select", prompt: "pusaq", audio: "pusaq", choices: ["Ocho", "Siete", "Nueve", "Diez"], answer: "Ocho" },
          { id: "p1u2l2e4", type: "select", prompt: "isqun", audio: "isqun", choices: ["Nueve", "Diez", "Ocho", "Siete"], answer: "Nueve" },
          { id: "p1u2l2e5", type: "select", prompt: "chunka", audio: "chunka", choices: ["Diez", "Nueve", "Once", "Doce"], answer: "Diez" },
          { id: "p1u2l2e6", type: "match", prompt: "Empareja", pairs: [
            { q: "suqta", a: "Seis" }, { q: "qanchis", a: "Siete" }, { q: "pusaq", a: "Ocho" }, { q: "isqun", a: "Nueve" }, { q: "chunka", a: "Diez" },
          ]},
          { id: "p1u2l2e7", type: "listen", prompt: "¿Qué número escuchaste?", audio: "chunka", choices: ["Diez", "Cinco", "Siete", "Ocho"], answer: "Diez" },
        ],
      },
      {
        id: "p1u2l3",
        title: "La Familia",
        emoji: "👨‍👩‍👧‍👦",
        description: "Conoce a los miembros de la familia",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p1u2l3e1", type: "select", prompt: "mama", audio: "mama", choices: ["Madre", "Padre", "Hijo", "Hermano"], answer: "Madre" },
          { id: "p1u2l3e2", type: "select", prompt: "tayta", audio: "tayta", choices: ["Padre", "Madre", "Tío", "Abuelo"], answer: "Padre" },
          { id: "p1u2l3e3", type: "select", prompt: "wawa", audio: "wawa", choices: ["Niño/a", "Hermano", "Primo", "Sobrino"], answer: "Niño/a" },
          { id: "p1u2l3e4", type: "select", prompt: "wawqi", audio: "wawqi", choices: ["Hermana", "Hermano", "Madre", "Tía"], answer: "Hermana" },
          { id: "p1u2l3e5", type: "select", prompt: "tura", audio: "tura", choices: ["Hermano", "Padre", "Tío", "Primo"], answer: "Hermano" },
          { id: "p1u2l3e6", type: "match", prompt: "Empareja la familia", pairs: [
            { q: "mama", a: "Madre" }, { q: "tayta", a: "Padre" }, { q: "wawa", a: "Niño/a" }, { q: "wawqi", a: "Hermana" },
          ]},
          { id: "p1u2l3e7", type: "reverse", prompt: "Madre", audio: "mama", choices: ["mama", "tayta", "wawa", "wawqi"], answer: "mama" },
        ],
      },
      {
        id: "p1u2l4",
        title: "Más Familia",
        emoji: "👴",
        description: "Abuelos, tíos y primos",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p1u2l4e1", type: "select", prompt: "apichu", audio: "apichu", choices: ["Abuela", "Abuelo", "Tía", "Tío"], answer: "Abuela" },
          { id: "p1u2l4e2", type: "select", prompt: "machu", audio: "machu", choices: ["Abuelo", "Abuela", "Padre", "Tío"], answer: "Abuelo" },
          { id: "p1u2l4e3", type: "select", prompt: "ipa", audio: "ipa", choices: ["Tía", "Tío", "Prima", "Sobrina"], answer: "Tía" },
          { id: "p1u2l4e4", type: "select", prompt: "kaka", audio: "kaka", choices: ["Tío", "Primo", "Abuelo", "Hermano"], answer: "Tío" },
          { id: "p1u2l4e5", type: "match", prompt: "Empareja", pairs: [
            { q: "apichu", a: "Abuela" }, { q: "machu", a: "Abuelo" }, { q: "ipa", a: "Tía" }, { q: "kaka", a: "Tío" },
          ]},
          { id: "p1u2l4e6", type: "bank", prompt: "Traduce: Mi abuelo", words: ["nuqaq", "machu", "mama", "tayta"], answer: ["nuqaq", "machu"] },
        ],
      },
    ],
  },
  {
    id: "p1u3",
    title: "Mes 1 · Semana 3",
    subtitle: "El Cuerpo Humano",
    color: "amber",
    emoji: "🧑",
    description: "Aprende las partes del cuerpo en quechua.",
    lessons: [
      {
        id: "p1u3l1",
        title: "Cara y Cabeza",
        emoji: "😐",
        description: "Ojos, orejas, boca y nariz",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p1u3l1e1", type: "select", prompt: "ñawi", audio: "ñawi", choices: ["Ojo", "Oreja", "Boca", "Nariz"], answer: "Ojo" },
          { id: "p1u3l1e2", type: "select", prompt: "rinri", audio: "rinri", choices: ["Oreja", "Ojo", "Nariz", "Boca"], answer: "Oreja" },
          { id: "p1u3l1e3", type: "select", prompt: "simi", audio: "simi", choices: ["Boca", "Ojo", "Oreja", "Diente"], answer: "Boca" },
          { id: "p1u3l1e4", type: "select", prompt: "senqa", audio: "senqa", choices: ["Nariz", "Boca", "Oreja", "Frente"], answer: "Nariz" },
          { id: "p1u3l1e5", type: "match", prompt: "Empareja la cara", pairs: [
            { q: "ñawi", a: "Ojo" }, { q: "rinri", a: "Oreja" }, { q: "simi", a: "Boca" }, { q: "senqa", a: "Nariz" },
          ]},
          { id: "p1u3l1e6", type: "reverse", prompt: "Ojo", audio: "ñawi", choices: ["ñawi", "rinri", "simi", "senqa"], answer: "ñawi" },
          { id: "p1u3l1e7", type: "listen", prompt: "¿Qué escuchaste?", audio: "simi", choices: ["Boca", "Ojo", "Nariz", "Oreja"], answer: "Boca" },
        ],
      },
      {
        id: "p1u3l2",
        title: "Manos y Pies",
        emoji: "✋",
        description: "Extremidades del cuerpo",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p1u3l2e1", type: "select", prompt: "maki", audio: "maki", choices: ["Mano", "Pie", "Brazo", "Pierna"], answer: "Mano" },
          { id: "p1u3l2e2", type: "select", prompt: "chaki", audio: "chaki", choices: ["Pie", "Mano", "Dedo", "Pierna"], answer: "Pie" },
          { id: "p1u3l2e3", type: "select", prompt: "maki ruru", audio: "maki ruru", choices: ["Dedo de mano", "Dedo de pie", "Muñeca", "Codo"], answer: "Dedo de mano" },
          { id: "p1u3l2e4", type: "reverse", prompt: "Pie", audio: "chaki", choices: ["chaki", "maki", "ñawi", "simi"], answer: "chaki" },
          { id: "p1u3l2e5", type: "match", prompt: "Empareja", pairs: [
            { q: "maki", a: "Mano" }, { q: "chaki", a: "Pie" }, { q: "ñawi", a: "Ojo" }, { q: "simi", a: "Boca" },
          ]},
          { id: "p1u3l2e6", type: "bank", prompt: "Traduce: Mi mano", words: ["nuqaq", "maki", "chaki", "ñawi"], answer: ["nuqaq", "maki"] },
        ],
      },
      {
        id: "p1u3l3",
        title: "Repaso del Cuerpo",
        emoji: "🧠",
        description: "Repasa todo lo aprendido",
        xpReward: 25,
        gemReward: 10,
        exercises: [
          { id: "p1u3l3e1", type: "match", prompt: "Empareja todo el cuerpo", pairs: [
            { q: "ñawi", a: "Ojo" }, { q: "rinri", a: "Oreja" }, { q: "simi", a: "Boca" }, { q: "senqa", a: "Nariz" }, { q: "maki", a: "Mano" }, { q: "chaki", a: "Pie" },
          ]},
          { id: "p1u3l3e2", type: "listen", prompt: "¿Qué escuchaste?", audio: "ñawi", choices: ["Ojo", "Oreja", "Boca", "Mano"], answer: "Ojo" },
          { id: "p1u3l3e3", type: "listen", prompt: "¿Qué escuchaste?", audio: "maki", choices: ["Mano", "Pie", "Ojo", "Boca"], answer: "Mano" },
          { id: "p1u3l3e4", type: "reverse", prompt: "Oreja", audio: "rinri", choices: ["rinri", "ñawi", "senqa", "simi"], answer: "rinri" },
          { id: "p1u3l3e5", type: "reverse", prompt: "Nariz", audio: "senqa", choices: ["senqa", "simi", "ñawi", "rinri"], answer: "senqa" },
        ],
      },
    ],
  },
  {
    id: "p1u4",
    title: "Mes 1 · Semana 4",
    subtitle: "Colores y Adjetivos",
    color: "amber",
    emoji: "🎨",
    description: "Aprende colores y descripciones básicas.",
    lessons: [
      {
        id: "p1u4l1",
        title: "Colores Básicos",
        emoji: "🌈",
        description: "Los colores del arcoíris andino",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p1u4l1e1", type: "select", prompt: "puka", audio: "puka", choices: ["Rojo", "Azul", "Verde", "Amarillo"], answer: "Rojo" },
          { id: "p1u4l1e2", type: "select", prompt: "ankas", audio: "ankas", choices: ["Azul", "Rojo", "Negro", "Verde"], answer: "Azul" },
          { id: "p1u4l1e3", type: "select", prompt: "umirana", audio: "umirana", choices: ["Verde", "Azul", "Blanco", "Negro"], answer: "Verde" },
          { id: "p1u4l1e4", type: "select", prompt: "kanqa", audio: "kanqa", choices: ["Amarillo", "Rojo", "Morado", "Gris"], answer: "Amarillo" },
          { id: "p1u4l1e5", type: "select", prompt: "yuraq", audio: "yuraq", choices: ["Blanco", "Negro", "Rojo", "Azul"], answer: "Blanco" },
          { id: "p1u4l1e6", type: "select", prompt: "yana", audio: "yana", choices: ["Negro", "Blanco", "Verde", "Amarillo"], answer: "Negro" },
          { id: "p1u4l1e7", type: "match", prompt: "Empareja los colores", pairs: [
            { q: "puka", a: "Rojo" }, { q: "ankas", a: "Azul" }, { q: "yuraq", a: "Blanco" }, { q: "yana", a: "Negro" },
          ]},
        ],
      },
      {
        id: "p1u4l2",
        title: "Adjetivos Básicos",
        emoji: "📏",
        description: "Grande, pequeño, bueno, malo",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p1u4l2e1", type: "select", prompt: "hatun", audio: "hatun", choices: ["Grande", "Pequeño", "Alto", "Bajo"], answer: "Grande" },
          { id: "p1u4l2e2", type: "select", prompt: "huch'uy", audio: "huch'uy", choices: ["Pequeño", "Grande", "Largo", "Corto"], answer: "Pequeño" },
          { id: "p1u4l2e3", type: "select", prompt: "allin", audio: "allin", choices: ["Bueno", "Malo", "Feo", "Hermoso"], answer: "Bueno" },
          { id: "p1u4l2e4", type: "select", prompt: "millay", audio: "millay", choices: ["Malo/Feo", "Bueno", "Hermoso", "Pequeño"], answer: "Malo/Feo" },
          { id: "p1u4l2e5", type: "select", prompt: "sumaq", audio: "sumaq", choices: ["Hermoso", "Feo", "Grande", "Malo"], answer: "Hermoso" },
          { id: "p1u4l2e6", type: "match", prompt: "Empareja adjetivos", pairs: [
            { q: "hatun", a: "Grande" }, { q: "huch'uy", a: "Pequeño" }, { q: "allin", a: "Bueno" }, { q: "sumaq", a: "Hermoso" },
          ]},
          { id: "p1u4l2e7", type: "reverse", prompt: "Hermoso", audio: "sumaq", choices: ["sumaq", "millay", "hatun", "allin"], answer: "sumaq" },
        ],
      },
      {
        id: "p1u4l3",
        title: "Repaso Mes 1",
        emoji: "🏁",
        description: "Repaso completo del primer mes",
        xpReward: 30,
        gemReward: 15,
        exercises: [
          { id: "p1u4l3e1", type: "match", prompt: "Empareja todo", pairs: [
            { q: "allinllachu", a: "Hola" }, { q: "sulpayki", a: "Gracias" }, { q: "mama", a: "Madre" }, { q: "huk", a: "Uno" },
          ]},
          { id: "p1u4l3e2", type: "select", prompt: "kimsa", audio: "kimsa", choices: ["Tres", "Dos", "Cuatro", "Cinco"], answer: "Tres" },
          { id: "p1u4l3e3", type: "reverse", prompt: "Rojo", audio: "puka", choices: ["puka", "ankas", "yuraq", "yana"], answer: "puka" },
          { id: "p1u4l3e4", type: "listen", prompt: "¿Qué escuchaste?", audio: "sumaq", choices: ["Hermoso", "Grande", "Bueno", "Pequeño"], answer: "Hermoso" },
          { id: "p1u4l3e5", type: "bank", prompt: "Traduce: Hasta luego", words: ["tupananchiskama", "allinllachu", "sulpayki", "allinmi"], answer: ["tupananchiskama"] },
        ],
      },
    ],
  },

  // ========== FASE 1: PRINCIPIANTE - MES 2 ==========
  {
    id: "p2u1",
    title: "Mes 2 · Semana 1",
    subtitle: "Naturaleza",
    color: "green",
    emoji: "🌍",
    description: "Sol, luna, estrellas, agua y fuego. La naturaleza andina.",
    lessons: [
      {
        id: "p2u1l1",
        title: "Sol y Luna",
        emoji: "☀️",
        description: "Inti y Killa, deidades andinas",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p2u1l1e1", type: "select", prompt: "inti", audio: "inti", choices: ["Sol", "Luna", "Estrella", "Cielo"], answer: "Sol" },
          { id: "p2u1l1e2", type: "select", prompt: "killa", audio: "killa", choices: ["Luna", "Sol", "Estrella", "Nube"], answer: "Luna" },
          { id: "p2u1l1e3", type: "select", prompt: "ch'aska", audio: "ch'aska", choices: ["Estrella", "Luna", "Sol", "Cometa"], answer: "Estrella" },
          { id: "p2u1l1e4", type: "select", prompt: "hanaq pacha", audio: "hanaq pacha", choices: ["Cielo", "Tierra", "Mar", "Montaña"], answer: "Cielo" },
          { id: "p2u1l1e5", type: "match", prompt: "Empareja el cielo", pairs: [
            { q: "inti", a: "Sol" }, { q: "killa", a: "Luna" }, { q: "ch'aska", a: "Estrella" }, { q: "hanaq pacha", a: "Cielo" },
          ]},
          { id: "p2u1l1e6", type: "reverse", prompt: "Sol", audio: "inti", choices: ["inti", "killa", "ch'aska", "pacha"], answer: "inti" },
          { id: "p2u1l1e7", type: "listen", prompt: "¿Qué escuchaste?", audio: "killa", choices: ["Luna", "Sol", "Estrella", "Cielo"], answer: "Luna" },
        ],
      },
      {
        id: "p2u1l2",
        title: "Agua y Fuego",
        emoji: "💧",
        description: "Elementos naturales",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p2u1l2e1", type: "select", prompt: "yaku", audio: "yaku", choices: ["Agua", "Fuego", "Tierra", "Aire"], answer: "Agua" },
          { id: "p2u1l2e2", type: "select", prompt: "nina", audio: "nina", choices: ["Fuego", "Agua", "Piedra", "Madera"], answer: "Fuego" },
          { id: "p2u1l2e3", type: "select", prompt: "allpa", audio: "allpa", choices: ["Tierra", "Agua", "Fuego", "Cielo"], answer: "Tierra" },
          { id: "p2u1l2e4", type: "select", prompt: "mayu", audio: "mayu", choices: ["Río", "Lago", "Mar", "Pozo"], answer: "Río" },
          { id: "p2u1l2e5", type: "select", prompt: "qucha", audio: "qucha", choices: ["Lago/Mar", "Río", "Arroyo", "Cascada"], answer: "Lago/Mar" },
          { id: "p2u1l2e6", type: "match", prompt: "Empareja elementos", pairs: [
            { q: "yaku", a: "Agua" }, { q: "nina", a: "Fuego" }, { q: "allpa", a: "Tierra" }, { q: "mayu", a: "Río" },
          ]},
          { id: "p2u1l2e7", type: "bank", prompt: "Traduce: El fuego", words: ["nina", "yaku", "allpa", "inti"], answer: ["nina"] },
        ],
      },
      {
        id: "p2u1l3",
        title: "Plantas y Árboles",
        emoji: "🌳",
        description: "Flora andina",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p2u1l3e1", type: "select", prompt: "sach'a", audio: "sach'a", choices: ["Árbol", "Flor", "Hierba", "Fruta"], answer: "Árbol" },
          { id: "p2u1l3e2", type: "select", prompt: "t'ika", audio: "t'ika", choices: ["Flor", "Árbol", "Hoja", "Raíz"], answer: "Flor" },
          { id: "p2u1l3e3", type: "select", prompt: "sara", audio: "sara", choices: ["Maíz", "Papa", "Quinua", "Trigo"], answer: "Maíz" },
          { id: "p2u1l3e4", type: "select", prompt: "papa", audio: "papa", choices: ["Papa", "Maíz", "Yuca", "Camote"], answer: "Papa" },
          { id: "p2u1l3e5", type: "match", prompt: "Empareja plantas", pairs: [
            { q: "sach'a", a: "Árbol" }, { q: "t'ika", a: "Flor" }, { q: "sara", a: "Maíz" }, { q: "papa", a: "Papa" },
          ]},
          { id: "p2u1l3e6", type: "reverse", prompt: "Maíz", audio: "sara", choices: ["sara", "papa", "sach'a", "t'ika"], answer: "sara" },
        ],
      },
    ],
  },
  {
    id: "p2u2",
    title: "Mes 2 · Semana 2",
    subtitle: "Animales",
    color: "emerald",
    emoji: "🦙",
    description: "Animales de los Andes y la selva peruana.",
    lessons: [
      {
        id: "p2u2l1",
        title: "Animales Andinos",
        emoji: "🦙",
        description: "Llama, alpaca, cóndor y más",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p2u2l1e1", type: "select", prompt: "llama", audio: "llama", choices: ["Llama", "Alpaca", "Vicuña", "Guanaco"], answer: "Llama" },
          { id: "p2u2l1e2", type: "select", prompt: "kuntur", audio: "kuntur", choices: ["Cóndor", "Águila", "Halcón", "Buitre"], answer: "Cóndor" },
          { id: "p2u2l1e3", type: "select", prompt: "waka", audio: "waka", choices: ["Vaca", "Toro", "Oveja", "Cabra"], answer: "Vaca" },
          { id: "p2u2l1e4", type: "select", prompt: "uwija", audio: "uwija", choices: ["Oveja", "Vaca", "Llama", "Cabra"], answer: "Oveja" },
          { id: "p2u2l1e5", type: "select", prompt: "alku", audio: "alku", choices: ["Perro", "Gato", "Zorro", "Lobo"], answer: "Perro" },
          { id: "p2u2l1e6", type: "match", prompt: "Empareja animales", pairs: [
            { q: "llama", a: "Llama" }, { q: "kuntur", a: "Cóndor" }, { q: "waka", a: "Vaca" }, { q: "alku", a: "Perro" },
          ]},
          { id: "p2u2l1e7", type: "reverse", prompt: "Cóndor", audio: "kuntur", choices: ["kuntur", "llama", "alku", "waka"], answer: "kuntur" },
        ],
      },
      {
        id: "p2u2l2",
        title: "Más Animales",
        emoji: "🐱",
        description: "Gato, caballo, cerdo y gallina",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p2u2l2e1", type: "select", prompt: "michi", audio: "michi", choices: ["Gato", "Perro", "Conejo", "Ratón"], answer: "Gato" },
          { id: "p2u2l2e2", type: "select", prompt: "kawallu", audio: "kawallu", choices: ["Caballo", "Burro", "Vaca", "Toro"], answer: "Caballo" },
          { id: "p2u2l2e3", type: "select", prompt: "kuchi", audio: "kuchi", choices: ["Cerdo", "Cabra", "Oveja", "Vaca"], answer: "Cerdo" },
          { id: "p2u2l2e4", type: "select", prompt: "p'unchu", audio: "p'unchu", choices: ["Gallina", "Pato", "Pavo", "Ganso"], answer: "Gallina" },
          { id: "p2u2l2e5", type: "match", prompt: "Empareja", pairs: [
            { q: "michi", a: "Gato" }, { q: "kawallu", a: "Caballo" }, { q: "kuchi", a: "Cerdo" }, { q: "p'unchu", a: "Gallina" },
          ]},
          { id: "p2u2l2e6", type: "listen", prompt: "¿Qué animal escuchaste?", audio: "michi", choices: ["Gato", "Perro", "Caballo", "Cerdo"], answer: "Gato" },
        ],
      },
      {
        id: "p2u2l3",
        title: "Pájaros y Peces",
        emoji: "🐦",
        description: "Aves y peces del Perú",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p2u2l3e1", type: "select", prompt: "pisqu", audio: "pisqu", choices: ["Pájaro", "Pez", "Mariposa", "Abeja"], answer: "Pájaro" },
          { id: "p2u2l3e2", type: "select", prompt: "challwa", audio: "challwa", choices: ["Pez", "Pájaro", "Rana", "Cangrejo"], answer: "Pez" },
          { id: "p2u2l3e3", type: "select", prompt: "phillwu", audio: "phillwu", choices: ["Mariposa", "Abeja", "Pájaro", "Mosca"], answer: "Mariposa" },
          { id: "p2u2l3e4", type: "reverse", prompt: "Pez", audio: "challwa", choices: ["challwa", "pisqu", "kuntur", "phillwu"], answer: "challwa" },
          { id: "p2u2l3e5", type: "match", prompt: "Empareja", pairs: [
            { q: "pisqu", a: "Pájaro" }, { q: "challwa", a: "Pez" }, { q: "phillwu", a: "Mariposa" }, { q: "kuntur", a: "Cóndor" },
          ]},
        ],
      },
    ],
  },
  {
    id: "p2u3",
    title: "Mes 2 · Semana 3",
    subtitle: "Comida y Bebida",
    color: "amber",
    emoji: "🥘",
    description: "Alimentos andinos: papa, maíz, sopa, pan.",
    lessons: [
      {
        id: "p2u3l1",
        title: "Alimentos Básicos",
        emoji: "🥔",
        description: "Papa, maíz, pan y frutas",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p2u3l1e1", type: "select", prompt: "papa", audio: "papa", choices: ["Papa", "Maíz", "Yuca", "Camote"], answer: "Papa" },
          { id: "p2u3l1e2", type: "select", prompt: "sara", audio: "sara", choices: ["Maíz", "Papa", "Quinua", "Trigo"], answer: "Maíz" },
          { id: "p2u3l1e3", type: "select", prompt: "t'anta", audio: "t'anta", choices: ["Pan", "Galleta", "Torta", "Harina"], answer: "Pan" },
          { id: "p2u3l1e4", type: "select", prompt: "kinwa", audio: "kinwa", choices: ["Quinua", "Maíz", "Papa", "Avena"], answer: "Quinua" },
          { id: "p2u3l1e5", type: "select", prompt: "chupi", audio: "chupi", choices: ["Sopa", "Pan", "Maíz", "Papa"], answer: "Sopa" },
          { id: "p2u3l1e6", type: "match", prompt: "Empareja alimentos", pairs: [
            { q: "papa", a: "Papa" }, { q: "sara", a: "Maíz" }, { q: "t'anta", a: "Pan" }, { q: "chupi", a: "Sopa" },
          ]},
          { id: "p2u3l1e7", type: "reverse", prompt: "Pan", audio: "t'anta", choices: ["t'anta", "chupi", "papa", "sara"], answer: "t'anta" },
        ],
      },
      {
        id: "p2u3l2",
        title: "Bebidas",
        emoji: "🥤",
        description: "Agua, chicha y otras bebidas",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p2u3l2e1", type: "select", prompt: "yaku", audio: "yaku", choices: ["Agua", "Leche", "Jugo", "Café"], answer: "Agua" },
          { id: "p2u3l2e2", type: "select", prompt: "aqha", audio: "aqha", choices: ["Chicha", "Cerveza", "Vino", "Jugo"], answer: "Chicha" },
          { id: "p2u3l2e3", type: "select", prompt: "ñukya", audio: "ñukya", choices: ["Leche", "Agua", "Chicha", "Café"], answer: "Leche" },
          { id: "p2u3l2e4", type: "reverse", prompt: "Chicha", audio: "aqha", choices: ["aqha", "yaku", "ñukya", "chupi"], answer: "aqha" },
          { id: "p2u3l2e5", type: "match", prompt: "Empareja bebidas", pairs: [
            { q: "yaku", a: "Agua" }, { q: "aqha", a: "Chicha" }, { q: "ñukya", a: "Leche" },
          ]},
        ],
      },
      {
        id: "p2u3l3",
        title: "Verbos de Comida",
        emoji: "🍽️",
        description: "Comer, beber, cocinar",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p2u3l3e1", type: "select", prompt: "mikhuy", audio: "mikhuy", choices: ["Comer", "Beber", "Cocinar", "Masticar"], answer: "Comer" },
          { id: "p2u3l3e2", type: "select", prompt: "upyay", audio: "upyay", choices: ["Beber", "Comer", "Cocinar", "Servir"], answer: "Beber" },
          { id: "p2u3l3e3", type: "select", prompt: "wayk'uy", audio: "wayk'uy", choices: ["Cocinar", "Comer", "Beber", "Lavar"], answer: "Cocinar" },
          { id: "p2u3l3e4", type: "match", prompt: "Empareja verbos", pairs: [
            { q: "mikhuy", a: "Comer" }, { q: "upyay", a: "Beber" }, { q: "wayk'uy", a: "Cocinar" },
          ]},
          { id: "p2u3l3e5", type: "bank", prompt: "Traduce: Yo como", words: ["nuqa", "mikhuni", "upyani", "wayk'uni"], answer: ["nuqa", "mikhuni"] },
        ],
      },
    ],
  },
  {
    id: "p2u4",
    title: "Mes 2 · Semana 4",
    subtitle: "Repaso y Práctica",
    color: "amber",
    emoji: "🔄",
    description: "Repaso completo del segundo mes.",
    lessons: [
      {
        id: "p2u4l1",
        title: "Repaso Naturaleza",
        emoji: "🌍",
        description: "Sol, luna, agua, fuego",
        xpReward: 25,
        gemReward: 10,
        exercises: [
          { id: "p2u4l1e1", type: "match", prompt: "Empareja todo", pairs: [
            { q: "inti", a: "Sol" }, { q: "killa", a: "Luna" }, { q: "yaku", a: "Agua" }, { q: "nina", a: "Fuego" }, { q: "allpa", a: "Tierra" },
          ]},
          { id: "p2u4l1e2", type: "listen", prompt: "¿Qué escuchaste?", audio: "inti", choices: ["Sol", "Luna", "Agua", "Fuego"], answer: "Sol" },
          { id: "p2u4l1e3", type: "reverse", prompt: "Tierra", audio: "allpa", choices: ["allpa", "yaku", "nina", "inti"], answer: "allpa" },
        ],
      },
      {
        id: "p2u4l2",
        title: "Repaso Animales y Comida",
        emoji: "🦙",
        description: "Animales y alimentos",
        xpReward: 25,
        gemReward: 10,
        exercises: [
          { id: "p2u4l2e1", type: "match", prompt: "Empareja animales", pairs: [
            { q: "llama", a: "Llama" }, { q: "kuntur", a: "Cóndor" }, { q: "alku", a: "Perro" }, { q: "waka", a: "Vaca" },
          ]},
          { id: "p2u4l2e2", type: "select", prompt: "sara", audio: "sara", choices: ["Maíz", "Papa", "Pan", "Sopa"], answer: "Maíz" },
          { id: "p2u4l2e3", type: "select", prompt: "mikhuy", audio: "mikhuy", choices: ["Comer", "Beber", "Cocinar", "Dormir"], answer: "Comer" },
          { id: "p2u4l2e4", type: "bank", prompt: "Traduce: El cóndor vuela", words: ["kuntur", "p'amparay", "mikhuy", "wayk'uy"], answer: ["kuntur", "p'amparay"] },
        ],
      },
    ],
  },

  // ========== FASE 1: PRINCIPIANTE - MES 3 ==========
  {
    id: "p3u1",
    title: "Mes 3 · Semana 1",
    subtitle: "Verbos Básicos",
    color: "green",
    emoji: "⚡",
    description: "Acciones cotidianas: caminar, hablar, ver, dormir.",
    lessons: [
      {
        id: "p3u1l1",
        title: "Acciones Diarias",
        emoji: "🚶",
        description: "Verbos esenciales",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p3u1l1e1", type: "select", prompt: "puriy", audio: "puriy", choices: ["Caminar", "Correr", "Saltar", "Bailar"], answer: "Caminar" },
          { id: "p3u1l1e2", type: "select", prompt: "rimay", audio: "rimay", choices: ["Hablar", "Escuchar", "Pensar", "Gritar"], answer: "Hablar" },
          { id: "p3u1l1e3", type: "select", prompt: "rikuway", audio: "rikuway", choices: ["Ver", "Oír", "Oler", "Tocar"], answer: "Ver" },
          { id: "p3u1l1e4", type: "select", prompt: "puñuy", audio: "puñuy", choices: ["Dormir", "Soñar", "Descansar", "Despertar"], answer: "Dormir" },
          { id: "p3u1l1e5", type: "select", prompt: "uyariy", audio: "uyariy", choices: ["Escuchar", "Hablar", "Ver", "Pensar"], answer: "Escuchar" },
          { id: "p3u1l1e6", type: "select", prompt: "qelqay", audio: "qelqay", choices: ["Escribir", "Leer", "Dibujar", "Pintar"], answer: "Escribir" },
          { id: "p3u1l1e7", type: "match", prompt: "Empareja verbos", pairs: [
            { q: "puriy", a: "Caminar" }, { q: "rimay", a: "Hablar" }, { q: "puñuy", a: "Dormir" }, { q: "uyariy", a: "Escuchar" },
          ]},
        ],
      },
      {
        id: "p3u1l2",
        title: "Más Verbos",
        emoji: "💪",
        description: "Trabajar, aprender, jugar",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p3u1l2e1", type: "select", prompt: "ruway", audio: "ruway", choices: ["Hacer/Trabajar", "Descansar", "Dormir", "Pensar"], answer: "Hacer/Trabajar" },
          { id: "p3u1l2e2", type: "select", prompt: "yachay", audio: "yachay", choices: ["Aprender/Saber", "Olvidar", "Enseñar", "Estudiar"], answer: "Aprender/Saber" },
          { id: "p3u1l2e3", type: "select", prompt: "pukllay", audio: "pukllay", choices: ["Jugar", "Bailar", "Cantar", "Correr"], answer: "Jugar" },
          { id: "p3u1l2e4", type: "select", prompt: "takiy", audio: "takiy", choices: ["Cantar", "Bailar", "Tocar", "Escuchar"], answer: "Cantar" },
          { id: "p3u1l2e5", type: "match", prompt: "Empareja", pairs: [
            { q: "ruway", a: "Hacer" }, { q: "yachay", a: "Aprender" }, { q: "pukllay", a: "Jugar" }, { q: "takiy", a: "Cantar" },
          ]},
          { id: "p3u1l2e6", type: "reverse", prompt: "Cantar", audio: "takiy", choices: ["takiy", "pukllay", "yachay", "ruway"], answer: "takiy" },
        ],
      },
      {
        id: "p3u1l3",
        title: "Conjugación Básica",
        emoji: "📝",
        description: "Yo, tú, él/ella",
        xpReward: 25,
        gemReward: 10,
        exercises: [
          { id: "p3u1l3e1", type: "select", prompt: "nuqa", audio: "nuqa", choices: ["Yo", "Tú", "Él/Ella", "Nosotros"], answer: "Yo" },
          { id: "p3u1l3e2", type: "select", prompt: "qam", audio: "qam", choices: ["Tú", "Yo", "Él/Ella", "Ellos"], answer: "Tú" },
          { id: "p3u1l3e3", type: "select", prompt: "pay", audio: "pay", choices: ["Él/Ella", "Yo", "Tú", "Nosotros"], answer: "Él/Ella" },
          { id: "p3u1l3e4", type: "select", prompt: "nuqayku", audio: "nuqayku", choices: ["Nosotros", "Yo", "Ellos", "Tú"], answer: "Nosotros" },
          { id: "p3u1l3e5", type: "match", prompt: "Empareja pronombres", pairs: [
            { q: "nuqa", a: "Yo" }, { q: "qam", a: "Tú" }, { q: "pay", a: "Él/Ella" }, { q: "nuqayku", a: "Nosotros" },
          ]},
          { id: "p3u1l3e6", type: "bank", prompt: "Traduce: Yo camino", words: ["nuqa", "purini", "rimani", "puñuni"], answer: ["nuqa", "purini"] },
        ],
      },
    ],
  },
  {
    id: "p3u2",
    title: "Mes 3 · Semana 2",
    subtitle: "Tiempo y Días",
    color: "emerald",
    emoji: "📅",
    description: "Días de la semana, meses y estaciones.",
    lessons: [
      {
        id: "p3u2l1",
        title: "Días y Tiempo",
        emoji: "📅",
        description: "Hoy, mañana, ayer",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p3u2l1e1", type: "select", prompt: "kunan p'unchaw", audio: "kunan p'unchaw", choices: ["Hoy", "Mañana", "Ayer", "Ahora"], answer: "Hoy" },
          { id: "p3u2l1e2", type: "select", prompt: "paqarin", audio: "paqarin", choices: ["Mañana", "Hoy", "Ayer", "Tarde"], answer: "Mañana" },
          { id: "p3u2l1e3", type: "select", prompt: "qayna p'unchaw", audio: "qayna p'unchaw", choices: ["Ayer", "Hoy", "Mañana", "Pasado mañana"], answer: "Ayer" },
          { id: "p3u2l1e4", type: "select", prompt: "tuta", audio: "tuta", choices: ["Noche", "Día", "Tarde", "Mañana"], answer: "Noche" },
          { id: "p3u2l1e5", type: "select", prompt: "p'unchaw", audio: "p'unchaw", choices: ["Día", "Noche", "Tarde", "Amanecer"], answer: "Día" },
          { id: "p3u2l1e6", type: "match", prompt: "Empareja tiempo", pairs: [
            { q: "kunan p'unchaw", a: "Hoy" }, { q: "paqarin", a: "Mañana" }, { q: "qayna p'unchaw", a: "Ayer" }, { q: "tuta", a: "Noche" },
          ]},
        ],
      },
      {
        id: "p3u2l2",
        title: "Estaciones",
        emoji: "🍂",
        description: "Las estaciones andinas",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p3u2l2e1", type: "select", prompt: "para mit'a", audio: "para mit'a", choices: ["Época de lluvia", "Época seca", "Verano", "Invierno"], answer: "Época de lluvia" },
          { id: "p3u2l2e2", type: "select", prompt: "ch'aki mit'a", audio: "ch'aki mit'a", choices: ["Época seca", "Época de lluvia", "Primavera", "Otoño"], answer: "Época seca" },
          { id: "p3u2l2e3", type: "select", prompt: "ratu", audio: "ratu", choices: ["Estación/Tiempo", "Día", "Noche", "Año"], answer: "Estación/Tiempo" },
          { id: "p3u2l2e4", type: "match", prompt: "Empareja estaciones", pairs: [
            { q: "para mit'a", a: "Lluvia" }, { q: "ch'aki mit'a", a: "Seca" }, { q: "ratu", a: "Estación" },
          ]},
        ],
      },
      {
        id: "p3u2l3",
        title: "Preguntas Básicas",
        emoji: "❓",
        description: "Qué, dónde, cuándo, cómo",
        xpReward: 25,
        gemReward: 10,
        exercises: [
          { id: "p3u2l3e1", type: "select", prompt: "ima", audio: "ima", choices: ["Qué", "Dónde", "Cuándo", "Cómo"], answer: "Qué" },
          { id: "p3u2l3e2", type: "select", prompt: "maypi", audio: "maypi", choices: ["Dónde", "Qué", "Cuándo", "Quién"], answer: "Dónde" },
          { id: "p3u2l3e3", type: "select", prompt: "imayna", audio: "imayna", choices: ["Cómo", "Qué", "Dónde", "Por qué"], answer: "Cómo" },
          { id: "p3u2l3e4", type: "select", prompt: "ima rayku", audio: "ima rayku", choices: ["Por qué", "Cómo", "Dónde", "Cuándo"], answer: "Por qué" },
          { id: "p3u2l3e5", type: "match", prompt: "Empareja preguntas", pairs: [
            { q: "ima", a: "Qué" }, { q: "maypi", a: "Dónde" }, { q: "imayna", a: "Cómo" }, { q: "ima rayku", a: "Por qué" },
          ]},
          { id: "p3u2l3e6", type: "bank", prompt: "Traduce: ¿Qué es esto?", words: ["ima", "kay", "puriy", "rimay"], answer: ["ima", "kay"] },
        ],
      },
    ],
  },
  {
    id: "p3u3",
    title: "Mes 3 · Semana 3",
    subtitle: "La Casa y Direcciones",
    color: "amber",
    emoji: "🏠",
    description: "Partes de la casa y direcciones básicas.",
    lessons: [
      {
        id: "p3u3l1",
        title: "La Casa",
        emoji: "🏠",
        description: "Casa, puerta, techo, cuarto",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p3u3l1e1", type: "select", prompt: "wasi", audio: "wasi", choices: ["Casa", "Puerta", "Techo", "Piso"], answer: "Casa" },
          { id: "p3u3l1e2", type: "select", prompt: "punku", audio: "punku", choices: ["Puerta", "Casa", "Ventana", "Techo"], answer: "Puerta" },
          { id: "p3u3l1e3", type: "select", prompt: "wichqana", audio: "wichqana", choices: ["Ventana", "Puerta", "Casa", "Piso"], answer: "Ventana" },
          { id: "p3u3l1e4", type: "select", prompt: "qata", audio: "qata", choices: ["Techo", "Piso", "Pared", "Puerta"], answer: "Techo" },
          { id: "p3u3l1e5", type: "match", prompt: "Empareja la casa", pairs: [
            { q: "wasi", a: "Casa" }, { q: "punku", a: "Puerta" }, { q: "wichqana", a: "Ventana" }, { q: "qata", a: "Techo" },
          ]},
          { id: "p3u3l1e6", type: "reverse", prompt: "Casa", audio: "wasi", choices: ["wasi", "punku", "qata", "wichqana"], answer: "wasi" },
        ],
      },
      {
        id: "p3u3l2",
        title: "Direcciones",
        emoji: "🧭",
        description: "Arriba, abajo, dentro, fuera",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p3u3l2e1", type: "select", prompt: "hanan", audio: "hanan", choices: ["Arriba", "Abajo", "Adentro", "Afuera"], answer: "Arriba" },
          { id: "p3u3l2e2", type: "select", prompt: "urin", audio: "urin", choices: ["Abajo", "Arriba", "Dentro", "Fuera"], answer: "Abajo" },
          { id: "p3u3l2e3", type: "select", prompt: "ukhupi", audio: "ukhupi", choices: ["Dentro", "Fuera", "Arriba", "Abajo"], answer: "Dentro" },
          { id: "p3u3l2e4", type: "select", prompt: "hawapi", audio: "hawapi", choices: ["Fuera", "Dentro", "Arriba", "Abajo"], answer: "Fuera" },
          { id: "p3u3l2e5", type: "match", prompt: "Empareja direcciones", pairs: [
            { q: "hanan", a: "Arriba" }, { q: "urin", a: "Abajo" }, { q: "ukhupi", a: "Dentro" }, { q: "hawapi", a: "Fuera" },
          ]},
        ],
      },
      {
        id: "p3u3l3",
        title: "Preposiciones",
        emoji: "📍",
        description: "En, sobre, bajo, junto a",
        xpReward: 20,
        gemReward: 5,
        exercises: [
          { id: "p3u3l3e1", type: "select", prompt: "patapi", audio: "patapi", choices: ["Sobre/Encima", "Bajo", "Junto a", "Lejos de"], answer: "Sobre/Encima" },
          { id: "p3u3l3e2", type: "select", prompt: "uriqpi", audio: "uriqpi", choices: ["Bajo/Debajo", "Sobre", "Junto a", "Delante"], answer: "Bajo/Debajo" },
          { id: "p3u3l3e3", type: "select", prompt: "kinraypi", audio: "kinraypi", choices: ["Junto a/Al lado", "Sobre", "Bajo", "Detrás"], answer: "Junto a/Al lado" },
          { id: "p3u3l3e4", type: "match", prompt: "Empareja preposiciones", pairs: [
            { q: "patapi", a: "Sobre" }, { q: "uriqpi", a: "Bajo" }, { q: "kinraypi", a: "Junto a" },
          ]},
        ],
      },
    ],
  },
  {
    id: "p3u4",
    title: "Mes 3 · Semana 4",
    subtitle: "Repaso Final Principiante",
    color: "amber",
    emoji: "🏆",
    description: "Repaso completo de los 3 meses. ¡Felicidades!",
    lessons: [
      {
        id: "p3u4l1",
        title: "Gran Repaso 1",
        emoji: "📖",
        description: "Saludos, números, familia",
        xpReward: 30,
        gemReward: 15,
        exercises: [
          { id: "p3u4l1e1", type: "match", prompt: "Empareja todo lo aprendido", pairs: [
            { q: "allinllachu", a: "Hola" }, { q: "sulpayki", a: "Gracias" }, { q: "huk", a: "Uno" }, { q: "mama", a: "Madre" },
          ]},
          { id: "p3u4l1e2", type: "select", prompt: "chunka", audio: "chunka", choices: ["Diez", "Cinco", "Siete", "Tres"], answer: "Diez" },
          { id: "p3u4l1e3", type: "reverse", prompt: "Padre", audio: "tayta", choices: ["tayta", "mama", "wawa", "wawqi"], answer: "tayta" },
          { id: "p3u4l1e4", type: "listen", prompt: "¿Qué escuchaste?", audio: "allinllachu", choices: ["Hola", "Gracias", "Adiós", "Perdón"], answer: "Hola" },
        ],
      },
      {
        id: "p3u4l2",
        title: "Gran Repaso 2",
        emoji: "🌍",
        description: "Naturaleza, animales, comida",
        xpReward: 30,
        gemReward: 15,
        exercises: [
          { id: "p3u4l2e1", type: "match", prompt: "Empareja naturaleza", pairs: [
            { q: "inti", a: "Sol" }, { q: "yaku", a: "Agua" }, { q: "llama", a: "Llama" }, { q: "papa", a: "Papa" },
          ]},
          { id: "p3u4l2e2", type: "select", prompt: "mikhuy", audio: "mikhuy", choices: ["Comer", "Dormir", "Caminar", "Hablar"], answer: "Comer" },
          { id: "p3u4l2e3", type: "bank", prompt: "Traduce: Yo como papa", words: ["nuqa", "papata", "mikhuni", "purini"], answer: ["nuqa", "papata", "mikhuni"] },
        ],
      },
      {
        id: "p3u4l3",
        title: "¡Graduación Principiante!",
        emoji: "🎓",
        description: "¡Felicidades! Has completado el nivel principiante",
        xpReward: 50,
        gemReward: 25,
        exercises: [
          { id: "p3u4l3e1", type: "select", prompt: "sumaq", audio: "sumaq", choices: ["Hermoso", "Feo", "Grande", "Malo"], answer: "Hermoso" },
          { id: "p3u4l3e2", type: "select", prompt: "yachay", audio: "yachay", choices: ["Aprender", "Olvidar", "Dormir", "Comer"], answer: "Aprender" },
          { id: "p3u4l3e3", type: "reverse", prompt: "Sol", audio: "inti", choices: ["inti", "killa", "yaku", "nina"], answer: "inti" },
          { id: "p3u4l3e4", type: "match", prompt: "Empareja todo", pairs: [
            { q: "allinllachu", a: "Hola" }, { q: "inti", a: "Sol" }, { q: "kuntur", a: "Cóndor" }, { q: "wasi", a: "Casa" },
          ]},
          { id: "p3u4l3e5", type: "bank", prompt: "Traduce: El cóndor es hermoso", words: ["kuntur", "sumaqmi", "millaymi", "hatunmi"], answer: ["kuntur", "sumaqmi"] },
        ],
      },
    ],
  },

  // ========== FASE 2: INTERMEDIO - MES 4 ==========
  {
    id: "i1u1",
    title: "Mes 4 · Intermedio",
    subtitle: "Gramática Quechua",
    color: "green",
    emoji: "📚",
    description: "Tiempos verbales, conjugación y estructuras gramaticales.",
    lessons: [
      {
        id: "i1u1l1",
        title: "Presente Continuo",
        emoji: "⏳",
        description: "Sufijo -sha: estar haciendo algo",
        xpReward: 25,
        gemReward: 10,
        exercises: [
          { id: "i1u1l1e1", type: "select", prompt: "mikhushani", audio: "mikhushani", choices: ["Estoy comiendo", "Comí", "Comeré", "Como"], answer: "Estoy comiendo" },
          { id: "i1u1l1e2", type: "select", prompt: "purishanki", audio: "purishanki", choices: ["Estás caminando", "Caminas", "Caminaste", "Caminarás"], answer: "Estás caminando" },
          { id: "i1u1l1e3", type: "select", prompt: "rimashan", audio: "rimashan", choices: ["Está hablando", "Habla", "Habló", "Hablará"], answer: "Está hablando" },
          { id: "i1u1l1e4", type: "reverse", prompt: "Estoy comiendo", audio: "mikhushani", choices: ["mikhushani", "mikhuni", "mikhurqani", "mikhusaq"], answer: "mikhushani" },
          { id: "i1u1l1e5", type: "match", prompt: "Empareja presente continuo", pairs: [
            { q: "mikhushani", a: "Estoy comiendo" }, { q: "purishanki", a: "Estás caminando" }, { q: "rimashan", a: "Está hablando" },
          ]},
          { id: "i1u1l1e6", type: "bank", prompt: "Traduce: Estoy durmiendo", words: ["puñushani", "mikhushani", "purishani", "rimashani"], answer: ["puñushani"] },
        ],
      },
      {
        id: "i1u1l2",
        title: "Tiempo Pasado",
        emoji: "⏮️",
        description: "Sufijo -rqa: acciones del pasado",
        xpReward: 25,
        gemReward: 10,
        exercises: [
          { id: "i1u1l2e1", type: "select", prompt: "mikhurqani", audio: "mikhurqani", choices: ["Comí", "Como", "Comeré", "Estoy comiendo"], answer: "Comí" },
          { id: "i1u1l2e2", type: "select", prompt: "purirqanki", audio: "purirqanki", choices: ["Caminaste", "Caminas", "Caminarás", "Estás caminando"], answer: "Caminaste" },
          { id: "i1u1l2e3", type: "select", prompt: "rimarqan", audio: "rimarqan", choices: ["Habló", "Habla", "Hablará", "Está hablando"], answer: "Habló" },
          { id: "i1u1l2e4", type: "reverse", prompt: "Comí", audio: "mikhurqani", choices: ["mikhurqani", "mikhuni", "mikhushani", "mikhusaq"], answer: "mikhurqani" },
          { id: "i1u1l2e5", type: "match", prompt: "Empareja pasado", pairs: [
            { q: "mikhurqani", a: "Comí" }, { q: "purirqanki", a: "Caminaste" }, { q: "rimarqan", a: "Habló" },
          ]},
        ],
      },
      {
        id: "i1u1l3",
        title: "Tiempo Futuro",
        emoji: "⏭️",
        description: "Sufijo -saq: acciones futuras",
        xpReward: 25,
        gemReward: 10,
        exercises: [
          { id: "i1u1l3e1", type: "select", prompt: "mikhusaq", audio: "mikhusaq", choices: ["Comeré", "Comí", "Como", "Estoy comiendo"], answer: "Comeré" },
          { id: "i1u1l3e2", type: "select", prompt: "purisaqki", audio: "purisaqki", choices: ["Caminarás", "Caminaste", "Caminas", "Estás caminando"], answer: "Caminarás" },
          { id: "i1u1l3e3", type: "select", prompt: "rimasaq", audio: "rimasaq", choices: ["Hablaré", "Hablé", "Hablo", "Estoy hablando"], answer: "Hablaré" },
          { id: "i1u1l3e4", type: "match", prompt: "Empareja futuro", pairs: [
            { q: "mikhusaq", a: "Comeré" }, { q: "purisaqki", a: "Caminarás" }, { q: "rimasaq", a: "Hablaré" },
          ]},
          { id: "i1u1l3e5", type: "bank", prompt: "Traduce: Dormiré", words: ["puñusaq", "mikhusaq", "purisaq", "rimasaq"], answer: ["puñusaq"] },
        ],
      },
    ],
  },
  {
    id: "i1u2",
    title: "Mes 4 · Intermedio",
    subtitle: "Conversación",
    color: "emerald",
    emoji: "💬",
    description: "Conversaciones cotidianas y frases útiles.",
    lessons: [
      {
        id: "i1u2l1",
        title: "Conversación Básica",
        emoji: "💬",
        description: "Diálogos cotidianos",
        xpReward: 25,
        gemReward: 10,
        exercises: [
          { id: "i1u2l1e1", type: "select", prompt: "imataq sutiyki", audio: "imataq sutiyki", choices: ["¿Cuál es tu nombre?", "¿Cómo estás?", "¿De dónde eres?", "¿Qué haces?"], answer: "¿Cuál es tu nombre?" },
          { id: "i1u2l1e2", type: "select", prompt: "sutiyqa", audio: "sutiyqa", choices: ["Mi nombre es", "Tu nombre es", "Su nombre es", "Nuestro nombre"], answer: "Mi nombre es" },
          { id: "i1u2l1e3", type: "select", prompt: "maymantataq hamunki", audio: "maymantataq hamunki", choices: ["¿De dónde vienes?", "¿A dónde vas?", "¿Cómo te llamas?", "¿Qué haces?"], answer: "¿De dónde vienes?" },
          { id: "i1u2l1e4", type: "select", prompt: "imataq ruwanki", audio: "imataq ruwanki", choices: ["¿Qué haces?", "¿Cómo estás?", "¿De dónde eres?", "¿Cuántos años tienes?"], answer: "¿Qué haces?" },
          { id: "i1u2l1e5", type: "match", prompt: "Empareja conversación", pairs: [
            { q: "imataq sutiyki", a: "¿Tu nombre?" }, { q: "sutiyqa", a: "Mi nombre" }, { q: "maymantataq hamunki", a: "¿De dónde vienes?" },
          ]},
          { id: "i1u2l1e6", type: "bank", prompt: "Traduce: Mi nombre es", words: ["sutiyqa", "imataq", "maypi", "imayna"], answer: ["sutiyqa"] },
        ],
      },
      {
        id: "i1u2l2",
        title: "Expresiones Útiles",
        emoji: "💡",
        description: "Frases para la vida diaria",
        xpReward: 25,
        gemReward: 10,
        exercises: [
          { id: "i1u2l2e1", type: "select", prompt: "mana yachanichu", audio: "mana yachanichu", choices: ["No sé", "Sé", "Entiendo", "No entiendo"], answer: "No sé" },
          { id: "i1u2l2e2", type: "select", prompt: "hamut'ay", audio: "hamut'ay", choices: ["Pienso", "Sé", "Creo", "Dudo"], answer: "Pienso" },
          { id: "i1u2l2e3", type: "select", prompt: "ari", audio: "ari", choices: ["Sí", "No", "Tal vez", "Claro"], answer: "Sí" },
          { id: "i1u2l2e4", type: "select", prompt: "mana", audio: "mana", choices: ["No", "Sí", "Tal vez", "Nunca"], answer: "No" },
          { id: "i1u2l2e5", type: "select", prompt: "pitucha", audio: "pitucha", choices: ["Tal vez", "Sí", "No", "Siempre"], answer: "Tal vez" },
          { id: "i1u2l2e6", type: "match", prompt: "Empareja expresiones", pairs: [
            { q: "mana yachanichu", a: "No sé" }, { q: "ari", a: "Sí" }, { q: "mana", a: "No" }, { q: "pitucha", a: "Tal vez" },
          ]},
        ],
      },
      {
        id: "i1u2l3",
        title: "Cultura Andina",
        emoji: "🏔️",
        description: "Tawantinsuyu, Pachamama, Inti Tayta",
        xpReward: 25,
        gemReward: 10,
        exercises: [
          { id: "i1u2l3e1", type: "select", prompt: "tawantinsuyu", audio: "tawantinsuyu", choices: ["Imperio Inca", "Cultura andina", "Montaña sagrada", "Padre Sol"], answer: "Imperio Inca" },
          { id: "i1u2l3e2", type: "select", prompt: "pachamama", audio: "pachamama", choices: ["Madre Tierra", "Padre Sol", "Luna sagrada", "Montaña"], answer: "Madre Tierra" },
          { id: "i1u2l3e3", type: "select", prompt: "inti tayta", audio: "inti tayta", choices: ["Padre Sol", "Madre Tierra", "Luna sagrada", "Estrella"], answer: "Padre Sol" },
          { id: "i1u2l3e4", type: "select", prompt: "apu", audio: "apu", choices: ["Montaña sagrada", "Río sagrado", "Lago sagrado", "Sol sagrado"], answer: "Montaña sagrada" },
          { id: "i1u2l3e5", type: "match", prompt: "Empareja cultura", pairs: [
            { q: "tawantinsuyu", a: "Imperio Inca" }, { q: "pachamama", a: "Madre Tierra" }, { q: "inti tayta", a: "Padre Sol" }, { q: "apu", a: "Montaña sagrada" },
          ]},
          { id: "i1u2l3e6", type: "reverse", prompt: "Madre Tierra", audio: "pachamama", choices: ["pachamama", "inti tayta", "apu", "tawantinsuyu"], answer: "pachamama" },
        ],
      },
    ],
  },
  {
    id: "i1u3",
    title: "Mes 4 · Intermedio",
    subtitle: "Vocabulario Ampliado",
    color: "amber",
    emoji: "📖",
    description: "Vocabulario intermedio: trabajo, emociones, clima.",
    lessons: [
      {
        id: "i1u3l1",
        title: "Trabajo y Ocupaciones",
        emoji: "💼",
        description: "Trabajos tradicionales andinos",
        xpReward: 25,
        gemReward: 10,
        exercises: [
          { id: "i1u3l1e1", type: "select", prompt: "chakra", audio: "chakra", choices: ["Chacra/Agricultura", "Casa", "Tienda", "Taller"], answer: "Chacra/Agricultura" },
          { id: "i1u3l1e2", type: "select", prompt: "maki", audio: "maki", choices: ["Trabajo manual", "Trabajo mental", "Descanso", "Canto"], answer: "Trabajo manual" },
          { id: "i1u3l1e3", type: "select", prompt: "tantay", audio: "tantay", choices: ["Reunir", "Separar", "Vender", "Comprar"], answer: "Reunir" },
          { id: "i1u3l1e4", type: "select", prompt: "mink'a", audio: "mink'a", choices: ["Trabajo comunitario", "Trabajo solo", "Descanso", "Fiesta"], answer: "Trabajo comunitario" },
          { id: "i1u3l1e5", type: "match", prompt: "Empareja trabajos", pairs: [
            { q: "chakra", a: "Agricultura" }, { q: "maki", a: "Trabajo manual" }, { q: "tantay", a: "Reunir" }, { q: "mink'a", a: "Trabajo comunitario" },
          ]},
        ],
      },
      {
        id: "i1u3l2",
        title: "Emociones",
        emoji: "😊",
        description: "Sentimientos en quechua",
        xpReward: 25,
        gemReward: 10,
        exercises: [
          { id: "i1u3l2e1", type: "select", prompt: "kusikuy", audio: "kusikuy", choices: ["Alegrarse", "Entristecerse", "Enojarse", "Asustarse"], answer: "Alegrarse" },
          { id: "i1u3l2e2", type: "select", prompt: "llakiy", audio: "llakiy", choices: ["Tristeza", "Alegría", "Enojo", "Miedo"], answer: "Tristeza" },
          { id: "i1u3l2e3", type: "select", prompt: "phiñakuy", audio: "phiñakuy", choices: ["Enojarse", "Alegrarse", "Asustarse", "Sorprenderse"], answer: "Enojarse" },
          { id: "i1u3l2e4", type: "select", prompt: "manchakuy", audio: "manchakuy", choices: ["Asustarse", "Alegrarse", "Enojarse", "Tristeza"], answer: "Asustarse" },
          { id: "i1u3l2e5", type: "match", prompt: "Empareja emociones", pairs: [
            { q: "kusikuy", a: "Alegría" }, { q: "llakiy", a: "Tristeza" }, { q: "phiñakuy", a: "Enojo" }, { q: "manchakuy", a: "Miedo" },
          ]},
        ],
      },
      {
        id: "i1u3l3",
        title: "Clima y Tiempo",
        emoji: "🌤️",
        description: "El clima en los Andes",
        xpReward: 25,
        gemReward: 10,
        exercises: [
          { id: "i1u3l3e1", type: "select", prompt: "para", audio: "para", choices: ["Lluvia", "Sol", "Viento", "Nieve"], answer: "Lluvia" },
          { id: "i1u3l3e2", type: "select", prompt: "wayra", audio: "wayra", choices: ["Viento", "Lluvia", "Sol", "Nube"], answer: "Viento" },
          { id: "i1u3l3e3", type: "select", prompt: "chiri", audio: "chiri", choices: ["Frío", "Calor", "Templado", "Húmedo"], answer: "Frío" },
          { id: "i1u3l3e4", type: "select", prompt: "q'unqu", audio: "q'unqu", choices: ["Calor", "Frío", "Viento", "Lluvia"], answer: "Calor" },
          { id: "i1u3l3e5", type: "match", prompt: "Empareja clima", pairs: [
            { q: "para", a: "Lluvia" }, { q: "wayra", a: "Viento" }, { q: "chiri", a: "Frío" }, { q: "q'unqu", a: "Calor" },
          ]},
        ],
      },
    ],
  },

  // ========== FASE 3: AVANZADO - MES 5 ==========
  {
    id: "a1u1",
    title: "Mes 5 · Avanzado",
    subtitle: "Expresiones Complejas",
    color: "green",
    emoji: "🎓",
    description: "Expresiones profundas y filosofía andina.",
    lessons: [
      {
        id: "a1u1l1",
        title: "Filosofía Andina",
        emoji: "🌌",
        description: "Sumaq kawsay, Pachakuti",
        xpReward: 30,
        gemReward: 15,
        exercises: [
          { id: "a1u1l1e1", type: "select", prompt: "sumaq kawsay", audio: "sumaq kawsay", choices: ["Buen vivir", "Mala vida", "Vida eterna", "Vida nueva"], answer: "Buen vivir" },
          { id: "a1u1l1e2", type: "select", prompt: "pachakuti", audio: "pachakuti", choices: ["Retorno del tiempo", "Fin del mundo", "Nueva era", "Cambio de estación"], answer: "Retorno del tiempo" },
          { id: "a1u1l1e3", type: "select", prompt: "ayni", audio: "ayni", choices: ["Reciprocidad", "Egoísmo", "Individualidad", "Competencia"], answer: "Reciprocidad" },
          { id: "a1u1l1e4", type: "select", prompt: "minka", audio: "minka", choices: ["Trabajo colectivo", "Trabajo individual", "Descanso", "Fiesta"], answer: "Trabajo colectivo" },
          { id: "a1u1l1e5", type: "match", prompt: "Empareja filosofía", pairs: [
            { q: "sumaq kawsay", a: "Buen vivir" }, { q: "pachakuti", a: "Retorno" }, { q: "ayni", a: "Reciprocidad" }, { q: "minka", a: "Trabajo colectivo" },
          ]},
          { id: "a1u1l1e6", type: "bank", prompt: "Traduce: Buen vivir", words: ["sumaq", "kawsay", "pachakuti", "ayni"], answer: ["sumaq", "kawsay"] },
        ],
      },
      {
        id: "a1u1l2",
        title: "Espiritualidad",
        emoji: "✨",
        description: "Conceptos espirituales andinos",
        xpReward: 30,
        gemReward: 15,
        exercises: [
          { id: "a1u1l2e1", type: "select", prompt: "waka", audio: "waka", choices: ["Lugar sagrado", "Casa común", "Montaña", "Río"], answer: "Lugar sagrado" },
          { id: "a1u1l2e2", type: "select", prompt: "despacho", audio: "despacho", choices: ["Ofrenda", "Rezo", "Canto", "Danza"], answer: "Ofrenda" },
          { id: "a1u1l2e3", type: "select", prompt: "willakuy", audio: "willakuy", choices: ["Narrar/Contar", "Escuchar", "Escribir", "Leer"], answer: "Narrar/Contar" },
          { id: "a1u1l2e4", type: "match", prompt: "Empareja espiritualidad", pairs: [
            { q: "waka", a: "Lugar sagrado" }, { q: "despacho", a: "Ofrenda" }, { q: "willakuy", a: "Narrar" },
          ]},
        ],
      },
      {
        id: "a1u1l3",
        title: "Literatura Quechua",
        emoji: "📜",
        description: "Poesía y tradiciones orales",
        xpReward: 30,
        gemReward: 15,
        exercises: [
          { id: "a1u1l3e1", type: "select", prompt: "harawi", audio: "harawi", choices: ["Poesía/Canto", "Prosa", "Cuento", "Novela"], answer: "Poesía/Canto" },
          { id: "a1u1l3e2", type: "select", prompt: "willay", audio: "willay", choices: ["Cuento/Historia", "Poesía", "Canción", "Rezo"], answer: "Cuento/Historia" },
          { id: "a1u1l3e3", type: "select", prompt: "taki", audio: "taki", choices: ["Canción", "Poema", "Cuento", "Discurso"], answer: "Canción" },
          { id: "a1u1l3e4", type: "match", prompt: "Empareja literatura", pairs: [
            { q: "harawi", a: "Poesía" }, { q: "willay", a: "Cuento" }, { q: "taki", a: "Canción" },
          ]},
          { id: "a1u1l3e5", type: "bank", prompt: "Traduce: Canto de poesía", words: ["harawi", "taki", "willay", "rimay"], answer: ["harawi", "taki"] },
        ],
      },
    ],
  },
  {
    id: "a1u2",
    title: "Mes 5 · Avanzado",
    subtitle: "Conversación Fluida",
    color: "emerald",
    emoji: "🗣️",
    description: "Conversaciones complejas y debates.",
    lessons: [
      {
        id: "a1u2l1",
        title: "Debates y Opiniones",
        emoji: "💭",
        description: "Expresar opiniones complejas",
        xpReward: 30,
        gemReward: 15,
        exercises: [
          { id: "a1u2l1e1", type: "select", prompt: "ñuqapa yuyayniy", audio: "ñuqapa yuyayniy", choices: ["En mi opinión", "Tu opinión", "Su opinión", "Nuestra opinión"], answer: "En mi opinión" },
          { id: "a1u2l1e2", type: "select", prompt: "chayna kayninqa", audio: "chayna kayninqa", choices: ["Así es", "No es así", "Tal vez", "No sé"], answer: "Así es" },
          { id: "a1u2l1e3", type: "select", prompt: "mana chaynachu", audio: "mana chaynachu", choices: ["No es así", "Así es", "Tal vez", "Claro"], answer: "No es así" },
          { id: "a1u2l1e4", type: "select", prompt: "yuyaysiway", audio: "yuyaysiway", choices: ["Piénsalo", "Hazlo", "Dilo", "Velo"], answer: "Piénsalo" },
          { id: "a1u2l1e5", type: "match", prompt: "Empareja opiniones", pairs: [
            { q: "ñuqapa yuyayniy", a: "En mi opinión" }, { q: "chayna kayninqa", a: "Así es" }, { q: "mana chaynachu", a: "No es así" },
          ]},
        ],
      },
      {
        id: "a1u2l2",
        title: "Conversación Compleja",
        emoji: "💬",
        description: "Diálogos avanzados",
        xpReward: 30,
        gemReward: 15,
        exercises: [
          { id: "a1u2l2e1", type: "select", prompt: "imamantataq kayqa", audio: "imamantataq kayqa", choices: ["¿De qué se trata esto?", "¿Qué es esto?", "¿Dónde está?", "¿Cuándo es?"], answer: "¿De qué se trata esto?" },
          { id: "a1u2l2e2", type: "select", prompt: "qamqa imataq ninkiiri", audio: "qamqa imataq ninkiiri", choices: ["¿Y tú qué dices?", "¿Qué haces?", "¿Cómo estás?", "¿Quién eres?"], answer: "¿Y tú qué dices?" },
          { id: "a1u2l2e3", type: "select", prompt: "mana allinchu icha", audio: "mana allinchu icha", choices: ["No es bueno, ¿verdad?", "Es bueno", "Tal vez", "No sé"], answer: "No es bueno, ¿verdad?" },
          { id: "a1u2l2e4", type: "bank", prompt: "Traduce: ¿Y tú qué dices?", words: ["qamqa", "imataq", "ninkiiri", "purinki"], answer: ["qamqa", "imataq", "ninkiiri"] },
        ],
      },
      {
        id: "a1u2l3",
        title: "Narrativa Avanzada",
        emoji: "📖",
        description: "Contar historias en quechua",
        xpReward: 30,
        gemReward: 15,
        exercises: [
          { id: "a1u2l3e1", type: "select", prompt: "huk p'unchaw", audio: "huk p'unchaw", choices: ["Un día", "Hoy", "Mañana", "Ayer"], answer: "Un día" },
          { id: "a1u2l3e2", type: "select", prompt: "qaynarqa", audio: "qaynarqa", choices: ["Había una vez", "Hoy", "Ahora", "Después"], answer: "Había una vez" },
          { id: "a1u2l3e3", type: "select", prompt: "chaymantataq", audio: "chaymantataq", choices: ["Y entonces", "Pero", "Porque", "Aunque"], answer: "Y entonces" },
          { id: "a1u2l3e4", type: "select", prompt: "chaypacha", audio: "chaypacha", choices: ["En ese tiempo", "Ahora", "Después", "Antes"], answer: "En ese tiempo" },
          { id: "a1u2l3e5", type: "match", prompt: "Empareja narrativa", pairs: [
            { q: "qaynarqa", a: "Había una vez" }, { q: "chaymantataq", a: "Y entonces" }, { q: "chaypacha", a: "En ese tiempo" },
          ]},
        ],
      },
    ],
  },
  {
    id: "a1u3",
    title: "Mes 5 · Avanzado",
    subtitle: "Graduación Final",
    color: "amber",
    emoji: "👑",
    description: "¡Última lección! Demuestra tu dominio del quechua.",
    lessons: [
      {
        id: "a1u3l1",
        title: "Examen Final 1",
        emoji: "📝",
        description: "Prueba tu conocimiento",
        xpReward: 40,
        gemReward: 20,
        exercises: [
          { id: "a1u3l1e1", type: "select", prompt: "sumaq kawsay", audio: "sumaq kawsay", choices: ["Buen vivir", "Mala vida", "Vida corta", "Vida nueva"], answer: "Buen vivir" },
          { id: "a1u3l1e2", type: "select", prompt: "pachamama", audio: "pachamama", choices: ["Madre Tierra", "Padre Sol", "Luna", "Estrella"], answer: "Madre Tierra" },
          { id: "a1u3l1e3", type: "reverse", prompt: "Buen vivir", audio: "sumaq kawsay", choices: ["sumaq kawsay", "pachakuti", "ayni", "minka"], answer: "sumaq kawsay" },
          { id: "a1u3l1e4", type: "match", prompt: "Empareja avanzado", pairs: [
            { q: "sumaq kawsay", a: "Buen vivir" }, { q: "pachakuti", a: "Retorno" }, { q: "ayni", a: "Reciprocidad" }, { q: "harawi", a: "Poesía" },
          ]},
          { id: "a1u3l1e5", type: "listen", prompt: "¿Qué escuchaste?", audio: "pachakuti", choices: ["Retorno del tiempo", "Buen vivir", "Reciprocidad", "Poesía"], answer: "Retorno del tiempo" },
        ],
      },
      {
        id: "a1u3l2",
        title: "Examen Final 2",
        emoji: "📊",
        description: "Vocabulario y gramática",
        xpReward: 40,
        gemReward: 20,
        exercises: [
          { id: "a1u3l2e1", type: "select", prompt: "mikhurqani", audio: "mikhurqani", choices: ["Comí", "Como", "Comeré", "Estoy comiendo"], answer: "Comí" },
          { id: "a1u3l2e2", type: "select", prompt: "purisaqki", audio: "purisaqki", choices: ["Caminarás", "Caminaste", "Caminas", "Estás caminando"], answer: "Caminarás" },
          { id: "a1u3l2e3", type: "reverse", prompt: "Estoy hablando", audio: "rimashani", choices: ["rimashani", "rimarqani", "rimani", "rimasaq"], answer: "rimashani" },
          { id: "a1u3l2e4", type: "bank", prompt: "Traduce: Yo comí papa", words: ["nuqa", "papata", "mikhurqani", "purirqani"], answer: ["nuqa", "papata", "mikhurqani"] },
        ],
      },
      {
        id: "a1u3l3",
        title: "¡Graduación Avanzada!",
        emoji: "🎓",
        description: "¡Felicidades! ¡Eres un hablante de quechua!",
        xpReward: 100,
        gemReward: 50,
        exercises: [
          { id: "a1u3l3e1", type: "select", prompt: "tawantinsuyu", audio: "tawantinsuyu", choices: ["Imperio Inca", "Montaña sagrada", "Padre Sol", "Madre Tierra"], answer: "Imperio Inca" },
          { id: "a1u3l3e2", type: "select", prompt: "kuntur", audio: "kuntur", choices: ["Cóndor", "Águila", "Llama", "Sol"], answer: "Cóndor" },
          { id: "a1u3l3e3", type: "reverse", prompt: "Filosofía del buen vivir", audio: "sumaq kawsay", choices: ["sumaq kawsay", "pachakuti", "ayni", "harawi"], answer: "sumaq kawsay" },
          { id: "a1u3l3e4", type: "match", prompt: "Empareja todo lo aprendido", pairs: [
            { q: "allinllachu", a: "Hola" }, { q: "inti", a: "Sol" }, { q: "pachamama", a: "Madre Tierra" }, { q: "sumaq kawsay", a: "Buen vivir" },
          ]},
          { id: "a1u3l3e5", type: "bank", prompt: "Traduce: La Madre Tierra es hermosa", words: ["pachamama", "sumaqmi", "millaymi", "hatunmi"], answer: ["pachamama", "sumaqmi"] },
          { id: "a1u3l3e6", type: "listen", prompt: "¿Qué escuchaste?", audio: "kuntur", choices: ["Cóndor", "Sol", "Luna", "Agua"], answer: "Cóndor" },
        ],
      },
    ],
  },
];
